SELECT * FROM FURIOUS_QUERYING.BI_TIEMPO

SELECT * FROM FURIOUS_QUERYING.BI_SUCURSAL

SELECT * FROM FURIOUS_QUERYING.BI_RANGO_ETARIO

SELECT * FROM FURIOUS_QUERYING.BI_TURNO

SELECT * FROM FURIOUS_QUERYING.BI_TIPO_MEDIO_DE_PAGO

SELECT * FROM FURIOUS_QUERYING.BI_MEDIO_DE_PAGO

SELECT * FROM FURIOUS_QUERYING.BI_SUBCATEGORIA

SELECT * FROM FURIOUS_QUERYING.BI_CATEGORIA

SELECT * FROM FURIOUS_QUERYING.BI_PROVINCIA

SELECT * FROM FURIOUS_QUERYING.BI_LOCALIDAD

SELECT * FROM FURIOUS_QUERYING.BI_TIPO_CAJA

SELECT * FROM FURIOUS_QUERYING.BI_HECHOS_VENTA

SELECT * FROM FURIOUS_QUERYING.BI_HECHOS_PAGO

SELECT * FROM FURIOUS_QUERYING.BI_HECHOS_PROMOCIONES_APLICADAS

SELECT * FROM FURIOUS_QUERYING.BI_HECHOS_ENVIO