GO
SELECT * FROM FURIOUS_QUERYING.TICKET_PROMEDIO_MENSUAL

GO
SELECT * FROM FURIOUS_QUERYING.CANTIDAD_UNIDADES_PROMEDIO

GO
SELECT * FROM FURIOUS_QUERYING.PORCENTAJE_VENTAS_X_RANGO_ETARIO

GO
SELECT * FROM FURIOUS_QUERYING.CANTIDAD_VENTAS_POR_TURNO

GO
SELECT * FROM FURIOUS_QUERYING.PORCENTAJE_DESCUENTO

GO
SELECT * FROM FURIOUS_QUERYING.CATEGORIAS_CON_MAYOR_DESCUENTO

GO
SELECT * FROM FURIOUS_QUERYING.PORCENTAJE_ENVIOS_CUMPLIDOS_A_TIEMPO

GO
SELECT * FROM FURIOUS_QUERYING.CANT_ENVIOS_RANGO_ETARIO_CLIENTES

GO
SELECT * FROM FURIOUS_QUERYING.LOCALIDADES_MAYOR_COSTO_ENVIO

GO
SELECT * FROM FURIOUS_QUERYING.SUCURSALES_MAYOR_IMPORTE_EN_CUOTAS

GO
SELECT * FROM FURIOUS_QUERYING.PROMEDIO_IMPORTE_CUOTA_POR_RANGO_ETARIO_DEL_CLIENTE

GO
SELECT * FROM FURIOUS_QUERYING.PORCENTAJE_DESCUENTO_POR_MEDIO_DE_PAGO